{% set version = "0.4.5" %}

package:
  name: fairlearn
  version: {{ version }}

source:
  url: https://github.com/fairlearn/fairlearn/archive/v{{ version }}.tar.gz
  sha256: 0db37f25285ea5c0fe90cfd1efb2e0c5ae4d22ac96f78c7132bb1b2e06a13c09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - fairlearn

about:
  home: https://github.com/fairlearn/fairlearn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and easy fairness assessment and unfairness mitigation

  description: |
    The fairlearn project seeks to enable anyone involved in the development of
    artificial intelligence (AI) systems to assess their system's fairness and
    mitigate the observed unfairness.
  doc_url: https://fairlearn.readthedocs.io/
  dev_url: https://github.com/fairlearn/fairlearn

extra:
  recipe-maintainers:
    - romanlutz
    - riedgar-ms
    - adrinjalali
